### PR TITLE
Change Looper Library

### PR DESCRIPTION
**Pull request by qemqemqem**
Major changes to the emergent/looper library

Usage can be seen here: https://github.com/emer/axon/blob/looper/examples/ra25/ra25.go

### CODE REVIEW

**Comment by rcoreilly** [comment]
quick comments:

* Remove `Loop` prefix from all names -- I thought we agreed that `looper.Loop*` is redundant.
* I thought we agreed on "Span" as the best name for what is now called "LoopSegment"
* Remove `IsPlusPhase` from "Span" -- not appropriate to have that kind of algorithm specific state in generic looping element.
* "Span" is called "Phase" in many places -- replace-all to make consistent.
* move Ctr into looper?

**Comment by rcoreilly** [comment]
Also would it make sense to add an "Add" method for IsDone methods?

Implement or remove?
```
func (loopman *LoopManager) Validate() *LoopManager {
	// TODO Make sure there are no duplicates.
	// TODO Print a note if there's a negative Max which will translate to looping forever.
	return loopman
}
```

Also run 'go vet' on the code and fix all those issues -- these code checks enforce basic go style and we use a standard badge to reflect the outcome of that check and a few others, but go vet covers most of it.

**Comment by rcoreilly** [comment]
* For Span, why doesn't it have a start counter? We want to enable overlapping spans right?  I just checked and phaseLogic indeed currently does not support overlapping.

* Should the Funcs there be called "OnStart" and "OnEnd" to be consistent with loops?

* btw the main thing I thought "go vet" would flag is lack of any documentation comments -- the best way to document the code is via these comments, which automatically generate the go.dev online documentation.  Turns out that is "golint" which is run on the standard go report thing.

**Comment by qemqemqem** [comment]
RE naming: Jed agreed with us that looper.LoopStack is clearer than looper.Stack and I think the same is true for looper.LoopSegment and looper.LoopManager. I think we agreed that Segment was better than Span; I've renamed local variables too.  

IsPlusPhase - removed

Ctr - moved into looper

IsDone doesn't need an Add method, but it could be added as a helper function in the future as needed. 

Validate - removed

Overlapping segments currently are not supported. We decided that that functionality is not currently needed. It could be added in the future, as needed. 

Functions renamed to OnStart and OnEnd. 

'go vet' ran, but doesn't find anything.

**Comment by rcoreilly** [comment]
while it is true that Jed said that about LoopStack but it really doesn't apply to anything else, and I would argue for consistency and general naming convention principles that it is much better to just leave it out of everything.  Seriously, this entire thing is about loops, there is no need to include the word "Loop" in front of everything.

Also, there was definitely a consensus that Span was better than segment -- Span conveys an arbitrary range of counter vals. 

Adding stuff in the future that is likely to be needed is not a great strategy for a core library like this -- we really don't want end users to have to go back and change all their code to accommodate the change.  Better to just add it and make a sensible default for non-overlapping.

Likewise for Add method on isdone -- I haven't checked on how you're using that, but without such a thing, the map itself doesn't seem to be initialized so how are you adding items there?  Again, we really don't want to have the change the api later..

Punting on docs?  this is not a great precedent -- if you don't write them now, when will you?? :)

**Comment by qemqemqem** [comment]
Regarding naming, my concern is with the use of generic words like "Stack" or "Span" to refer to specific things that do not have general capability. I'm OK with removing the word Loop from the class names, but can you think of names that are more specific? 

I'm indifferent to Segment vs Span. I can see how the word "Span" makes more sense if they overlap.

RE overlapping segments/spans. I think it's a software engineering mistake to implement that sort of thing without actively using it. Even if we expect to use it two weeks from now, it's still speculative to implement now, and there's a possibility it will lead to dead code or require changes in the future anyway. The code is designed such that it will be easy to add the capability to make them overlap in the future without breaking backwards compatibility; simply add a Start attribute to the object and check it in the loop logic. 

Same with an Add method on IsDone. If that's something you want later, it's easy to add to the interface. Note that this doesn't require changing the interface, so it won't mess up backward compatibility. But there's no reason to add it now without using it. 

Regarding docs, sorry, I wasn't sure what you meant. What docs need to be added where, and how do I see a report on what docs are needed?

**Comment by rcoreilly** [comment]
It is literally: `looper.Span`, `looper.Stack` -- I really don't see how that could possibly be ambiguous, and comparing that with `looper.LoopSpan` -- please try to convince me that "stuttering" like that represents a better naming scheme?  This is one of the most widely used and accepted principles of go naming, present in the base docs for go style, and used throughout the emer codebase.. https://stackoverflow.com/questions/45885985/ways-to-avoid-stuttering-in-go-package-and-struct-names

Re the Span starting counter -- I think we will want to *immediately* replace the switch statements for encoding ActS1 etc with span elements that have a specific start counter and duration 1, and also use these for scheduling things like lrate changes and weight file checkpointing -- much cleaner than big switch statements as we discussed in the meeting last week!

**Comment by qemqemqem** [comment]
The problem with something like looper.Stack is that "Stack" is a pretty generic term, and it's hard to know what it does. Imagine these hypothetical names and try to guess what they do: etime.Set, egui.List, elog.Increment, chem.First. I don't know about you, but I find those names to be confusing and mysterious, and I would need to look at the code to understand what they do. "LoopStack" clarifies that it's a stack of loops, rather than a stack of something else that might be in the looper library, such as counters or funcs. 

I think it helps to imagine seeing the name as someone who isn't very familiar with the code. It might be the case that while we're actively developing it, we can keep the details in memory and just need a shorter name to remind us what it is, but for less frequent contributors and for ourselves in the future, more specific names are helpful. 

I also think, as a matter of preference, Michael, Jed, and Erdal all prefer longer names and specifically prefer looper.LoopStack over looper.Stack, for the reasons I mention above.

**Comment by rcoreilly** [comment]
In practice, people just copy and modify existing example code. If there is any kind of initial confusion about what kind of Stack it is, it will vanish very quickly.  The naming conventions are more about readability of the code and aesthetic / stylistic factors.  One of the great things about the Go framework is that they explicitly remove as many degrees of freedom in this space as possible, through the use of tools like gofmt, specifically to avoid people spending too much time on debates like we are now having. The established, well-documented Go naming conventions are intended to play that same role: prevent people from wasting time debating things like this, and just going with these conventions. This is one of the things I really like about Go, and many people highlight as a major benefit of the broader ecosystem: you focus on what matters, and not on things that ultimately don't matter that much.

So, while it might be useful to have this discussion now, as the first instance of code you are contributing to the core infrastructure of the emer codebase, I hope we can please adopt these standard Go conventions here and going forward, and just focus on things of greater importance :)

**Comment by qemqemqem** [comment]
The official documentation <https://go.dev/doc/effective_go#names> on names
is quite short. It describes the naming of interfaces, which we do not
follow, and does not give much advice on what to name variables. Instead I
will quote from this commentary
<https://betterprogramming.pub/naming-conventions-in-go-short-but-descriptive-1fa7c6d2f32a>
on names in Go:

"Shorthand names are recommended when possible as long as they are easy to
> understand by anyone reading the code for the first time. The wider the
> scope of use is, the more it needs to be descriptive."
>

I think that's good advice and other websites give similar rules. I think
this indicates that we should use longer names if they are clearer, as in
this case. In general, my impression of the codebase is that it errs on the
side of unhelpfully short names. Please see my reasons gives above for why
a longer name like LoopStack is clearer in this case and therefore worth
the extra letters:

   1. "Stack" is a generic term, and should not be used for a non-generic
   object
   2. It's not clear what the Stack is of, even if you specify
   looper.Stack; it could be a stack of Funcs. looper.LoopStack clarifies
   3. Jed, Michael, and Erdal agree
   4. Longer names will be clearer to first time contributors and ourselves
   when we return to the code in the future


Yeah, I mostly think naming isn't that important, so I don't want to argue
about it too much. But I do want the code to be readable! And unfortunately
the official Go documentation here is quite short.

On the different topic of documentation, what's the best way to see where
documentation is needed? Or, what comments should I put in?

**Comment by qemqemqem** [comment]
| In practice, people just copy and modify existing example code

RE copying code. I think that might work better in an academic setting than in a larger software project with many collaborators. In general, the best practice is to minimize the amount of code that needs to be copied by creating good libraries that are easy to use and well documented (including with descriptive names). To the extent that code needs to be copied, it should be a slim skeleton. I think the refactoring we've been doing will really help with that.

**Comment by rcoreilly** [comment]
Docs: take a look at this or any other such pages: https://pkg.go.dev/github.com/emer/emergent@v1.2.2/elog -- these descriptions and info are generated by the // comments above types, functions etc.  See the `elog` or any other `emer` package for source code examples, and https://go.dev/doc/effective_go#commentary for official standards..

May I suggest that such comments would be an excellent place to inform any potentially confused parties about what kind of stack it is: :)

```Go
// Stack is a stack of loops
type Stack ...
```

The relevant part of the official docs https://go.dev/doc/effective_go on naming is here:
> The importer of a package will use the name to refer to its contents, so exported names in the package can use that fact to avoid repetition. (Don't use the import . notation, which can simplify tests that must run outside the package they are testing, but should otherwise be avoided.) For instance, the buffered reader type in the bufio package is called Reader, not BufReader, because users see it as bufio.Reader, which is a clear, concise name.

> Similarly, the function to make new instances of ring.Ring—which is the definition of a constructor in Go—would normally be called NewRing, but since Ring is the only type exported by the package, and since the package is called ring, it's called just New, which clients of the package see as ring.New. Use the package structure to help you choose good names.

According to this logic, if `Stack` did *not* refer to a stack of loops, then it would make sense to further qualify that, e.g., `FuncStack`, but once you see `looper.Stack`, you can safely assume it is a stack of loops, unless otherwise specified, in the same way that `ring.New` returns a new `Ring`.  Anyone who has significant experience with Go, upon seeing `looper.LoopStack` will have the same kind viceral reaction that I do: it does not fit with the standard.

Further info is found here: https://go.dev/blog/package-names, under the section on "Naming package contents"

**Comment by qemqemqem** [comment]
Well, I've changed the class names to not include Loop in them. But I'm not
convinced that it's the right thing to do; I still think these concise
names are harming the readability of the package.

I also added comments to all the methods.

**Comment by rcoreilly** [comment]
This is looking good -- if you could just remove the "Data" from "DataManager" I will be completely satisfied :)

**Comment by rcoreilly** [comment]
oh and rename span.go -> event.go

**Comment by rcoreilly** [comment]
It would be great to make "printControlFlow" exported -- as is, an end user cannot take advantage of this important feature when debugging issues with sims.

**Comment by rcoreilly** [comment]
I'm just running the test with printControlFlow = true -- seeing that it does not print below Trial level -- if you think this is important, how about adding another global setting with this cutoff level -- I can definitely imagine cases where you want to have the full trace to see what is going on with cycles etc.

**Comment by rcoreilly** [comment]
Sorry for all the spam.. :)  

The Step method in the step_test.go file should be a method on Stepper.  There are likely cases where someone will want to step through things in code, not just in the gui.  Likewise, when you call TestAll from within the Train code, you need a RunMode(mode) method that takes the mode as an arg.  Furthermore, you need an InitMode(mode) method that takes the mode and initializes the counters -- I don't see that anywhere -- how does the Init button work?

A few other issues:

```Go
	manager.Steps.Init(manager)
```

cleaner if you just call manager.Init() and it calls Steps.Init with its own pointer.

```Go
	manager.Stacks[etime.Train] = &Stack{}
	manager.Stacks[etime.Train].Init()...
```

simpler to just have Stacks.AddStack(etime.Train) that does equivalent of Init() and returns the stack so times can be added thereafter..

**Comment by rcoreilly** [comment]
using test that I just pushed, there is an issue in the timing of the OnStart call in stepping:

```
=== RUN   TestStep
#### Step Cyc 1:
Run:Start:0
Epoch:Start:0
Trial:Start:0
Cycle:Start:0
Cycle:End:  0
#### Step Cyc 1:
Skipping start: Run:0
Skipping start: Epoch:0
Skipping start: Trial:0
Cycle:Start:1
Cycle:End:  1
#### Step Cyc 1:
Skipping start: Run:0
Skipping start: Epoch:0
Skipping start: Trial:0
Cycle:Start:2
Cycle:End:  2
Trial:End:  0
Trial:Start:1    <- issue here: would be better if didn't call start of next trial when you just stepped off end of lower level
#### Step Cyc 1:
Skipping start: Run:0
Skipping start: Epoch:0
Skipping start: Trial:1
Cycle:Start:0
Cycle:End:  0
#### Step Cyc 2:
Skipping start: Run:0
Skipping start: Epoch:0
Skipping start: Trial:1
Cycle:Start:1
Cycle:End:  1
Cycle:Start:2
Cycle:End:  2
Trial:End:  1
Trial:Start:2  <- same issue again
```

As you can see, it does the Start of the next trial when you step to the max of the lower level.  In the gui, this means that you think you've just finished the end of a trial, and should expect to be seeing the end of the plus phase, but in fact it is now showing the start of the next trial, which presumably clears / decays activations, presents the new input pattern etc.  This would be very confusing, and doesn't match the correct behavior when you step at the Trial level.

**Pull request merged**
