### PR TITLE
Reduce the size of the envlp.Env interface by removing unnecessary functions to make it easier to implement

### PR DESCRIPTION
**Pull request by qemqemqem**

### CODE REVIEW

**Comment by rcoreilly** [comment]
We need Action right?  it can just be nil but in interactive envs, you need an interface for that.  Otherwise the other things are reasonable.  String is very handy for providing a label in the netview / trial log to reflect what is going on.

**Comment by StephenJRead** [comment]
I would say that you definitely need Action.

Stephen J. Read, Mendel B. Silberberg Professor of Social Psychology
3620 McClintock Ave, 821 SGM
University of Southern California
Los Angeles, CA 90089-1061
***@***.******@***.***>

On Apr 26, 2022, at 2:48 PM, rcoreilly ***@***.******@***.***>> wrote:



We need Action right? it can just be nil but in interactive envs, you need an interface for that. Otherwise the other things are reasonable. String is very handy for providing a label in the netview / trial log to reflect what is going on.

**Comment by qemqemqem** [comment]
I guess I'm not sure what this interface is for. Actions definitely occur,
but does looper need to know about them?

**Comment by rcoreilly** [comment]
This is the Env interface, not the looper one.  It needs to encapsulate the core functionality of an Env so that sims can generically call "Action" on an environment, in the same way they call "State"..

**Comment by jedmccaleb** [comment]
Is this going to get pulled in or can I close it?

**Comment by qemqemqem** [comment]
I would prefer to delete the entire envlp module, but up to Randy.

**Pull request closed without merging**
